//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitProvider) DeepCopyInto(out *GitProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitProvider.
func (in *GitProvider) DeepCopy() *GitProvider {
	if in == nil {
		return nil
	}
	out := new(GitProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemote) DeepCopyInto(out *GitRemote) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemote.
func (in *GitRemote) DeepCopy() *GitRemote {
	if in == nil {
		return nil
	}
	out := new(GitRemote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitRemote) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteList) DeepCopyInto(out *GitRemoteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitRemote, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteList.
func (in *GitRemoteList) DeepCopy() *GitRemoteList {
	if in == nil {
		return nil
	}
	out := new(GitRemoteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitRemoteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteSpec) DeepCopyInto(out *GitRemoteSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.CustomGitProvider = in.CustomGitProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteSpec.
func (in *GitRemoteSpec) DeepCopy() *GitRemoteSpec {
	if in == nil {
		return nil
	}
	out := new(GitRemoteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRemoteStatus) DeepCopyInto(out *GitRemoteStatus) {
	*out = *in
	in.LastAuthTime.DeepCopyInto(&out.LastAuthTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRemoteStatus.
func (in *GitRemoteStatus) DeepCopy() *GitRemoteStatus {
	if in == nil {
		return nil
	}
	out := new(GitRemoteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitUserBinding) DeepCopyInto(out *GitUserBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitUserBinding.
func (in *GitUserBinding) DeepCopy() *GitUserBinding {
	if in == nil {
		return nil
	}
	out := new(GitUserBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitUserBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitUserBindingList) DeepCopyInto(out *GitUserBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitUserBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitUserBindingList.
func (in *GitUserBindingList) DeepCopy() *GitUserBindingList {
	if in == nil {
		return nil
	}
	out := new(GitUserBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitUserBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitUserBindingSpec) DeepCopyInto(out *GitUserBindingSpec) {
	*out = *in
	out.Subject = in.Subject
	if in.RemoteRefs != nil {
		in, out := &in.RemoteRefs, &out.RemoteRefs
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitUserBindingSpec.
func (in *GitUserBindingSpec) DeepCopy() *GitUserBindingSpec {
	if in == nil {
		return nil
	}
	out := new(GitUserBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitUserBindingStatus) DeepCopyInto(out *GitUserBindingStatus) {
	*out = *in
	if in.GitUserHosts != nil {
		in, out := &in.GitUserHosts, &out.GitUserHosts
		*out = make([]GitUserHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUsedTime.DeepCopyInto(&out.LastUsedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitUserBindingStatus.
func (in *GitUserBindingStatus) DeepCopy() *GitUserBindingStatus {
	if in == nil {
		return nil
	}
	out := new(GitUserBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitUserHost) DeepCopyInto(out *GitUserHost) {
	*out = *in
	out.SecretRef = in.SecretRef
	in.LastUsedTime.DeepCopyInto(&out.LastUsedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitUserHost.
func (in *GitUserHost) DeepCopy() *GitUserHost {
	if in == nil {
		return nil
	}
	out := new(GitUserHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastBypassedObjectState) DeepCopyInto(out *LastBypassedObjectState) {
	*out = *in
	in.LastBypassedObjectTime.DeepCopyInto(&out.LastBypassedObjectTime)
	out.LastBypassedObjectSubject = in.LastBypassedObjectSubject
	in.LastBypassedObject.DeepCopyInto(&out.LastBypassedObject)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastBypassedObjectState.
func (in *LastBypassedObjectState) DeepCopy() *LastBypassedObjectState {
	if in == nil {
		return nil
	}
	out := new(LastBypassedObjectState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastInterceptedObjectState) DeepCopyInto(out *LastInterceptedObjectState) {
	*out = *in
	in.LastInterceptedObjectTime.DeepCopyInto(&out.LastInterceptedObjectTime)
	out.LastInterceptedObjectKubernetesUser = in.LastInterceptedObjectKubernetesUser
	in.LastInterceptedObject.DeepCopyInto(&out.LastInterceptedObject)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastInterceptedObjectState.
func (in *LastInterceptedObjectState) DeepCopy() *LastInterceptedObjectState {
	if in == nil {
		return nil
	}
	out := new(LastInterceptedObjectState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastPushedObjectState) DeepCopyInto(out *LastPushedObjectState) {
	*out = *in
	in.LastPushedObjectTime.DeepCopyInto(&out.LastPushedObjectTime)
	in.LastPushedObject.DeepCopyInto(&out.LastPushedObject)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastPushedObjectState.
func (in *LastPushedObjectState) DeepCopy() *LastPushedObjectState {
	if in == nil {
		return nil
	}
	out := new(LastPushedObjectState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceScopedKinds) DeepCopyInto(out *NamespaceScopedKinds) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIVersions != nil {
		in, out := &in.APIVersions, &out.APIVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceScopedKinds.
func (in *NamespaceScopedKinds) DeepCopy() *NamespaceScopedKinds {
	if in == nil {
		return nil
	}
	out := new(NamespaceScopedKinds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceScopedObject) DeepCopyInto(out *NamespaceScopedObject) {
	*out = *in
	in.APIGroups.DeepCopyInto(&out.APIGroups)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceScopedObject.
func (in *NamespaceScopedObject) DeepCopy() *NamespaceScopedObject {
	if in == nil {
		return nil
	}
	out := new(NamespaceScopedObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesInterceptor) DeepCopyInto(out *ResourcesInterceptor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesInterceptor.
func (in *ResourcesInterceptor) DeepCopy() *ResourcesInterceptor {
	if in == nil {
		return nil
	}
	out := new(ResourcesInterceptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourcesInterceptor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesInterceptorList) DeepCopyInto(out *ResourcesInterceptorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourcesInterceptor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesInterceptorList.
func (in *ResourcesInterceptorList) DeepCopy() *ResourcesInterceptorList {
	if in == nil {
		return nil
	}
	out := new(ResourcesInterceptorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourcesInterceptorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesInterceptorSpec) DeepCopyInto(out *ResourcesInterceptorSpec) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]OperationType, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedUsers != nil {
		in, out := &in.AuthorizedUsers, &out.AuthorizedUsers
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.BypassInterceptionSubjects != nil {
		in, out := &in.BypassInterceptionSubjects, &out.BypassInterceptionSubjects
		*out = make([]rbacv1.Subject, len(*in))
		copy(*out, *in)
	}
	if in.DefaultUserBind != nil {
		in, out := &in.DefaultUserBind, &out.DefaultUserBind
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.IncludedResources != nil {
		in, out := &in.IncludedResources, &out.IncludedResources
		*out = make([]NamespaceScopedKinds, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludedResources != nil {
		in, out := &in.ExcludedResources, &out.ExcludedResources
		*out = make([]NamespaceScopedKinds, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExcludedFields != nil {
		in, out := &in.ExcludedFields, &out.ExcludedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesInterceptorSpec.
func (in *ResourcesInterceptorSpec) DeepCopy() *ResourcesInterceptorSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcesInterceptorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesInterceptorStatus) DeepCopyInto(out *ResourcesInterceptorStatus) {
	*out = *in
	in.LastBypassedObjectState.DeepCopyInto(&out.LastBypassedObjectState)
	in.LastInterceptedObjectState.DeepCopyInto(&out.LastInterceptedObjectState)
	in.LastPushedObjectState.DeepCopyInto(&out.LastPushedObjectState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesInterceptorStatus.
func (in *ResourcesInterceptorStatus) DeepCopy() *ResourcesInterceptorStatus {
	if in == nil {
		return nil
	}
	out := new(ResourcesInterceptorStatus)
	in.DeepCopyInto(out)
	return out
}
