name: Architecture discussion
about: Suggest a change or having some question
title: '[AD] '
labels: bug
assignees: ''
body:
  - type: markdown
    id: discussion-subject
    attributes:
      - label: Discussion subject
        placeholder: |
          - [ ] Details needed
          - [ ] Change suggestion
    validations:
      required: true
  - type: textarea
    id: architecture-part
    attributes:
      - label: Architecture part concerned
        description: RemoteUser, webhooks, the reconcile function of the RemoteSyncer object, ...
    validations:
      required: true
  - type: textarea
    id: question-suggestion
    attributes:
      - label: Question / Suggestion
        description: |
          - Question or need details about the architecture.
          - Give a suggestion to improve the architecture
    validations:
      required: true
