apiVersion: syngit.syngit.io/v2alpha2
kind: RemoteSyncer
metadata:
  labels:
    app.kubernetes.io/name: remotesyncer
    app.kubernetes.io/instance: remotesyncer-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remotesyncer-sample
  namespace: test
spec:
  remoteRepository: ""
  branch: second-main
  commitMode: Commit
  commitProcess: CommitOnly
# bypassInterceptionSubjects:
    #- name: kubernetes-admin
    #  kind: User
  authorizedUsers:
    - name: remoteuserbinding-sample
  defaultUnauthorizedUserMode: Block
  excludedFields:
    - metadata.managedFields
    - metadata.creationTimestamp
    - metadata.annotations.[kubectl.kubernetes.io/last-applied-configuration]
    - metadata.uid
    - metadata.resourceVersion
  includedResources:
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["configmaps", "pods"]
        operations: ["CREATE", "UPDATE", "DELETE"]
