---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remoteuserbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-remoteuserbinding-viewer-role
rules:
- apiGroups:
  - syngit.syngit.io
  resources:
  - remoteuserbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.syngit.io
  resources:
  - remoteuserbindings/status
  verbs:
  - get
