apiVersion: syngit.syngit.io/v1alpha1
kind: RemoteUser
metadata:
  labels:
    app.kubernetes.io/name: remoteuser
    app.kubernetes.io/instance: remoteuser-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remoteuser-sample
  namespace: test
spec:
  gitBaseDomainFQDN: "gitlab.com"
  testAuthentication: true
  email: ""
  secretRef:
    name: secret-basic-auth
