name: Tests upgrade

on:
  # run it on push to the default repository branch
  push:
    branches:
      - '*'
  pull_request:

jobs:

  test-helm-upgrade:
    name: Helm upgrade test
    permissions: {}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

    - name: Install kubectl
      uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f #v4.0.0
      with:
        version: 'latest'

    - name: Set up KinD
      uses: helm/kind-action@fa81e57adff234b2908110485695db0f181f3c67 #v1.7.0
      with:
        version: v0.23.0
        cluster_name: syngit-dev-cluster

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Run tests
      run: make test-chart-upgrade